name: vcloud
description: A Dart SDK for the V.cloud API, providing tools for building virtual collaboration solutions.
version: 0.1.0
homepage: https://github.com/VCONNCT-TECH/vcloud_flutter_sdk
repository: https://github.com/VCONNCT-TECH/vcloud_flutter_sdk
environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  intl:  ^0.20.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
